name: "🚀 Feature Request: [기능 요약]"
description: "새로운 기능 추가 요청"
labels: [ "feature", "enhancement" ]
assignees:
  - ""

body:
  - type: textarea
    attributes:
      label: 📌 Related Issue
      description: |
        - close [이슈번호]
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🚀 Description
      description: |
        - commit 내역 적기
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📢 Notes
      description: |
        - 향후 개발을 위한 참고 사항을 기록